### ISSUE TITLE
Feature  Request (README) or Bug Fix: Sequence Identifier clarification needed

### ISSUE THREAD

**Issue by mmelendrez** [averagehat/Haskell-MAAPs#3]
Please clarify in the README how many characters are allowed in the sequence identifier to 'show up' in the output. I had 4 conditions all beginning with "Q4":

```
Q4_1_NexteraRawCons
Q4_1_KAPARawCons
Q4_6_NexteraRawCons
Q4_6_KAPARawCons
```

The output - 

```
ID      Codon   NTPos   AA      AAPos   RowType

Q4      RAA     1444    K/E     482     Non_Synonymous
Q4      TWC     1676    Y/F     559     Non_Synonymous
Q4      ARC     4025    N/S     1342    Non_Synonymous
Q4      GAW     5991    E/D     1997    Non_Synonymous

Q4      RAA     1444    K/E     482     Non_Synonymous
Q4      TWC     1676    Y/F     559     Non_Synonymous
Q4      RCC     5620    T/A     1874    Non_Synonymous

Q4      RAA     1444    K/E     482     Non_Synonymous
Q4      TWC     1676    Y/F     559     Non_Synonymous

Q4      RAA     1444    K/E     482     Non_Synonymous
Q4      TWC     1676    Y/F     559     Non_Synonymous
Q4      RTR     7939,7941       I/M/V   2647    Non_Synonymous
```

As you can see I don't know which conditions is which as the identifiers were cut off. So it would be helpful to know how many characters I am allowed or that an underscore won't work in identifier names etc...

**Comment by averagehat** [comment]
Right now it takes all characters until it encounters a separator "-" or
"_" or " " or the like. I could take the whole identifier instead. That
might make the table a bit harder to read as a plain text file but I think
it's better to use the whole identifier.

**Comment by mmelendrez** [comment]
Agreed - if the name is a headache that's the investigators issue, not yours
